//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInformatyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZamowienieKlienta
    {
        public int ZamowienieID { get; set; }
        public int KursID { get; set; }
        public int Ilość { get; set; }
        public int RabatProc { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual Zamowienie Zamowienie { get; set; }
    }
}
