//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektInformatyczny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamowienie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zamowienie()
        {
            this.ZamowienieKlienta = new HashSet<ZamowienieKlienta>();
        }
    
        public int ZamowienieID { get; set; }
        public System.DateTime DataZamowienia { get; set; }
        public bool CzyZrealizowane { get; set; }
        public int KlientID { get; set; }
        public int KursID { get; set; }
        public bool CzyFaktura { get; set; }
    
        public virtual Klient Klient { get; set; }
        public virtual Kurs Kurs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZamowienieKlienta> ZamowienieKlienta { get; set; }
    }
}
